spring.application.name=notificationservice

#SQL DB connection config
spring.datasource.url=jdbc:mysql://localhost:3307/notification_system
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

#redis cloud connection config
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

#Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.linger.ms=1

#Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.properties.session.timeout.ms=45000
spring.kafka.properties.request.timeout.ms=30000
spring.kafka.properties.delivery.timeout.ms=120000